[package]
name = "onnx-test-suite"
version = "0.20.7-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
bytes.workspace = true
fs2.workspace = true
lazy_static.workspace = true
log.workspace = true
prost.workspace = true
tract-core = { path = "../../core", version = "=0.20.7-pre" }
tract-nnef = { path = "../../nnef", version = "=0.20.7-pre" }
tract-onnx = { path = "../../onnx", version = "=0.20.7-pre" }
test-suite-utils = { path = "../test-suite-utils" }
gen-onnx-test-suite = { path = "../gen-onnx-test-suite" }

[features]
onnx_1_4_1 =  ["gen-onnx-test-suite/onnx_1_4_1"]
onnx_1_5_0 =  ["gen-onnx-test-suite/onnx_1_5_0"]
onnx_1_6_0 =  ["gen-onnx-test-suite/onnx_1_6_0"]
onnx_1_7_0 =  ["gen-onnx-test-suite/onnx_1_7_0"]
onnx_1_8_1 =  ["gen-onnx-test-suite/onnx_1_8_1"]
onnx_1_9_0 =  ["gen-onnx-test-suite/onnx_1_9_0"]
onnx_1_10_2 = ["gen-onnx-test-suite/onnx_1_10_2"]
onnx_1_11_0 = ["gen-onnx-test-suite/onnx_1_11_0"]
onnx_1_12_0 = ["gen-onnx-test-suite/onnx_1_12_0"]
onnx_1_13_0 = ["gen-onnx-test-suite/onnx_1_13_0"]
default = [ "onnx_1_13_0" ]

[dev-dependencies]
lazy_static.workspace = true

[build-dependencies]
fs2.workspace = true
gen-onnx-test-suite = { path = "../gen-onnx-test-suite" }
