[package]
name = "tract-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
boow = "0.1.3"
half.workspace = true
ndarray.workspace = true
tract-rs-sys = { path = "sys", version = "=0.20.0-pre" }

[dev-dependencies]
tempfile = "*"
serde_json = "*"
