[package]
name = "core-proptest-conv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tract-core = { path = "../../core" }
proptest.workspace = true
env_logger.workspace = true
