[package]
name = "gen-onnx-test-suite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs2.workspace = true

[features]
onnx_1_4_1 = []
onnx_1_5_0 = []
onnx_1_6_0 = []
onnx_1_7_0 = []
onnx_1_8_1 = []
onnx_1_9_0 = []
onnx_1_10_2 = []
onnx_1_11_0 = []
onnx_1_12_0 = []
onnx_1_13_0 = []
default = [ "onnx_1_13_0" ]
