[package]
name = "tract-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
boow.workspace = true
ndarray.workspace = true
tract-api = { path = ".." }
tract-rs-sys = { path = "sys" }

[dev-dependencies]
reqwest.workspace = true
tempfile = "*"
serde_json = "*"
