[package]
name = "onnx-to-nnef"
version = "0.1.0"
edition = "2021"

[dependencies]
dyn-clone.workspace = true
fs2.workspace = true
log.workspace = true
prost.workspace = true
tract-core = { path = "../../core", version = "=0.20.7-pre" }
tract-nnef = { path = "../../nnef", version = "=0.20.7-pre" }
tract-onnx = { path = "../../onnx", version = "=0.20.7-pre" }

[build-dependencies]
gen-onnx-test-suite = { path = "../gen-onnx-test-suite" }

[dev-dependencies]
gen-onnx-test-suite = { path = "../gen-onnx-test-suite" }
bytes.workspace = true
env_logger.workspace = true
lazy_static.workspace = true
log.workspace = true
onnx-test-suite = { path = "../onnx-test-suite" }
